# Generated by Django 4.2.27 on 2026-04-02 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_movie_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='liked',
        ),
        migrations.AddField(
            model_name='movie',
            name='watchlisted_by',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
